### ISSUE TITLE
Numbers for the rate distortion upper bound

### ISSUE THREAD

**Issue by duanzhiihao** [mandt-lab/empirical-RD-sandwich#1]
Hi, thanks for your great work! Your paper helps me a lot in understanding lossy compression.

Is it possible to release the exact numbers of your rate-distortion upper bound for natural images? I can visually see the curves in Figure 3 and Figure 11. I would like to compare methods to it numerically, but I cannot find exact numbers in the paper. It would be great if we can know the rate (bpp) distortion (either MSE or PSNR is okay) numbers estimated by ResNet-VAE for Kodak images.

**Comment by yiboyang** [comment]
Hi, thanks for your interest! The results from the figures are now added [here](https://github.com/mandt-lab/RD-sandwich/tree/master/results/img_compression/aggregate). I also added detailed results for individual images [here](https://github.com/mandt-lab/RD-sandwich/tree/master/results/img_compression/raw).

**Comment by duanzhiihao** [comment]
Thank you a lot for your detailed feedback! This is very helpful. It is also interesting that there is still such a large margin to improve lossy coders towards the theoretical R-D.
